version: '3.8'

services:
  app:
    build: .
    container_name: web-apache
    volumes:
      - .:/var/www/html
    command: >
      sh -c "composer install && composer dump-autoload && service cron start && apache2-foreground"
    env_file:
      - .env
    environment:
    - TZ=America/Sao_Paulo
    ports:
      - "80:80"
    platform: linux/amd64

  db:
    image: mysql:5.7
    container_name: db-mysql
    env_file:
      - .env
    environment:
    - TZ=America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/amd64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadm
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "9090:80"
    platform: linux/amd64
    

volumes:
  db_data:
